FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o campaigns_scrapper ./cmd/campaigns_scrapper

FROM alpine:3.18

WORKDIR /app

COPY --from=builder /app/campaigns_scrapper /app/campaigns_scrapper

CMD ["./campaigns_scrapper"]
