version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: candhis_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - candhis_network

  migrate:
    image: migrate/migrate
    container_name: migrate
    depends_on:
      - postgres
    volumes:
      - ./infra/db/migrations:/migrations
    entrypoint: [
      "migrate", 
      "-path", "/migrations", 
      "-database", "postgres://user:password@postgres:5432/candhis_db?sslmode=disable",
      "up"
    ]
    networks:
      - candhis_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - candhis_network

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.1.0
    container_name: metricbeat
    user: root
    volumes:
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /:/hostfs:ro
      - ./infra/metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch_logs:9200
    networks:
      - logs_network
    depends_on:
      - elasticsearch_logs

  elasticsearch_logs:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.0
    container_name: elasticsearch_logs
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9201:9200"
      - "9301:9300"
    volumes:
      - es_logs_data:/usr/share/elasticsearch/data
    networks:
      - logs_network

  fluentd:
    build:
      context: ./infra/fluentd
      dockerfile: Dockerfile
    container_name: fluentd
    depends_on:
      - elasticsearch_logs
    environment:
      FLUENT_ELASTICSEARCH_HOST: elasticsearch_logs
      FLUENT_ELASTICSEARCH_PORT: 9200
    volumes:
      - ./infra/fluentd/fluent.conf:/fluentd/etc/fluent.conf
      - /var/log/journal:/var/log/journal
    networks:
      - logs_network

  kibana_logs:
    image: docker.elastic.co/kibana/kibana:8.1.0
    container_name: kibana_logs
    depends_on:
      - elasticsearch_logs
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch_logs:9200
      - SERVER_HOST=0.0.0.0
    ports:
      - "5601:5601"
    networks:
      - logs_network

volumes:
  postgres_data:
  es_data:
  es_logs_data:

networks:
  candhis_network:
  logs_network: