---
- name: Ensure the target directory exists on the remote host
  file:
    path: /home/astraydev/candhis_api
    state: directory
    mode: '0755'
  tags:
    - sync_src

- name: Synchronize the repository files to the target directory
  synchronize:
    src: "{{ src_path }}"
    dest: /home/astraydev/candhis_api
    recursive: yes
    delete: yes
  tags:
    - sync_src