---
- name: Ensure Docker Compose is up for PostgreSQL
  shell: /usr/local/bin/docker-compose -f /home/astraydev/candhis_api/docker-compose.yml up -d postgres
  args:
    chdir: /home/astraydev/candhis_api

- name: Run database migrations
  shell: /usr/local/bin/docker-compose -f /home/astraydev/candhis_api/docker-compose.yml run --rm migrate
  args:
    chdir: /home/astraydev/candhis_api

- name: Insert a new session ID and date into candhis_session table
  shell: |
    /usr/local/bin/docker-compose exec -T postgres psql -U postgres -d your_database_name -c "
    WITH check_empty AS (
      SELECT COUNT(*) AS cnt FROM session_candhis
    )
    INSERT INTO session_candhis (id, created_at)
    SELECT 'noob_ID', NOW()
    FROM check_empty
    WHERE cnt = 0;
    "
  args:
    chdir: /home/astraydev/candhis_api
