openapi: 3.1.0
info:
  title: Candhis API
  version: 0.1.0
  description: Candhis API specification.
servers:
  - url: http://localhost/api/v1
tags:
  - name: monitoring
    description: Application monitoring
paths:
  /ping:
    get:
      tags:
        - monitoring
      description: Returns pong
      operationId: ping
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pong'
  /waves:
    get:
      tags:
        - waves
      description: Returns waves data
      operationId: waves
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Waves'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Pong:
      $ref: './schemas/pong.yml'
    Error:
      $ref: './schemas/error.yml'
    Waves:
      $ref: './schemas/waves.yml'