name: Deploy Binaries

on:
  workflow_call:
    secrets:
      ANSIBLE_SSH_PRIVATE_KEY:
        required: true
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Go environment
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build binaries using Makefile
      run: make build

    - name: Run playbook to install application
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: playbooks/install_app.yml
        directory: ./infra/ansible
        key: ${{secrets.ANSIBLE_SSH_PRIVATE_KEY}}
        inventory: |
          [servers]
          95.179.209.34 ansible_user=root
        known_hosts: |
          95.179.209.34 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHgzdQxG8sQQwzPEfiJkoUwtTWJ4nLOKkiiInfJJRdEI
          95.179.209.34 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCuuFKl0doae6LziEkmNlVKVTwNIwP6dzTzwVhhCQIv1YihWsHKDwM+PkgJDTwhQ0z+EjWjmnCoveQAL13xmpYwf6RDxDP4XW7jf3FC8G8MsRbs+kgoCrz9QkkE2MUTzpNriWTiGSmjzWegQ389Y20APzcW7l44mZLNCpogfOGFaGKg4o5I0NPalaQRlI37uXGRLi8lkII1/vv1U3sH/uXNmv3HwzeYu2fc8/mk3S/qElxvwArEeb1K7nPhK6zDXsT2e4+4xFxjloMynrcryDIBg7DWOxM2TwkJzZaOrCSacubV3jyu7NgU2w+klkQzqJSbqB9RiQsdcdyi1RebLhP58S3eEVHSIlpH4cnOxPvJff2Tam9U2JcU3Pa9glRAlTftW6Ga/bEQTR0/3/kqKpamtNII0hsA1WaIFfVIL3hFJ27hoqWi3Bu8ZRvYtyJZsoHgrB7LA+1G3gij6n2Z13Q19wfu8EVWLu0I1JIxbI0lLlxneHYcSfCwYcqv56FNg/U=
          95.179.209.34 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKUgH/wyaZZULvrYkiUPh5Uj75Gw91bTqxlDN8jgWZbAWGisJ2d9D8+CBUaGCGM7LKuzPQgrX63YBtDLdWwgiyA=
        options: |
          -vvv
