name: Deploy Application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test_unit:
    uses: ./.github/workflows/test_unit.yml
    secrets:
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
      SONAR_ORG: ${{ secrets.SONAR_ORG }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  test_integration:
    uses: ./.github/workflows/test_integration.yml

  # deploy_binaries:
  #   needs: [lint, test_unit, test_integration]
  #   uses: ./.github/workflows/deploy_binaries.yml
  #   secrets:
  #     ANSIBLE_SSH_PRIVATE_KEY: ${{secrets.ANSIBLE_SSH_PRIVATE_KEY}}
