name: Go Lint

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "*" ]
    workflow_call:  

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.23 

      - name: Install golangci-lint
        run: |
          make deps_lint

      - name: Run golangci-lint
        run: |
          make lint