name: E2E tests

on:
  pull_request:
    branches: [ "*" ]
  workflow_call:


jobs:
  e2e_tests:
    name: Run E2E tests
    runs-on: ubuntu-latest
    steps:
        - name: Check out the repository
          uses: actions/checkout@v4

        - name: Set up Docker Compose
          uses: adambirds/docker-compose-action@v1.5.0
          with:
            services: |
              postgres
              migrate
              elasticsearch
              api

        - name: Wait for Elasticsearch to be ready
          run: |
            until curl -s http://localhost:9200/_cluster/health | grep -q '"status":"green"'; do
              echo "Waiting for Elasticsearch..."
              sleep 5
            done  

        - name: Run and wait for Headless Chrome to be ready
          run: |
            make chrome-headless
            until curl -s http://localhost:9222/json/version | grep -q 'webSocketDebuggerUrl'; do
              echo "Waiting for Headless Chrome..."
              sleep 5
            done


        - name: Set up Go environment
          uses: actions/setup-go@v5
          with:
            go-version: 1.23

        - name: Run End-to-End Tests
          run: make download test-e2e
