name: integration tests

on:
  pull_request:
    branches: [ "*" ]
  workflow_call:

jobs:
    integration_tests:
        name: Run integration tests
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - uses: adambirds/docker-compose-action@v1.5.0
          with:
            services: |
                postgres
                migrate
        - uses: actions/setup-go@v4
          with:
            go-version: 1.23
    
        - name: Integration tests
          run: make download test-integration