name: unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]
  workflow_call:

jobs:
  unit_tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: 1.23

    - name: Unit test
      run: make download deps_test test-unit

    - name: Upload coverage to SonarCloud
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        sonar-scanner \
        -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
        -Dsonar.organization=${{ secrets.SONAR_ORG }} \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.go.coverage.reportPaths=cover.out

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        projectBaseDir: .
        args: >
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
          -Dsonar.organization=${{ secrets.SONAR_ORG }}
          -Dsonar.go.coverage.reportPaths=cover.out